# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOne', models.CharField(max_length=200, verbose_name='Address 1')),
                ('addressTwo', models.CharField(max_length=200, verbose_name='Address 2')),
                ('postalCode', models.IntegerField(verbose_name='Postal Code')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryName', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount', models.FloatField(primary_key=True, serialize=False, verbose_name='Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('productColor', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productSKU', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='SKU')),
                ('productName', models.CharField(max_length=200, verbose_name='Product Name')),
                ('productDesc', models.TextField(default=None, verbose_name='Description')),
                ('productPrice', models.FloatField(default=0, verbose_name='Price')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NUBER.Category')),
                ('productColor', models.ManyToManyField(to='NUBER.ProductColor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('productSize', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Size')),
                ('waistSize', models.CharField(default=None, max_length=5, verbose_name='Waist')),
                ('lowHipSize', models.CharField(default=None, max_length=5, verbose_name='Low Hip')),
                ('thighSize', models.CharField(default=None, max_length=5, verbose_name='Thigh')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shippingName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Shipping Name')),
                ('shippingDesc', models.TextField(verbose_name='Description')),
                ('shippingPrice', models.FloatField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('userCreated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('userStatus', models.BooleanField(default=True, verbose_name='Status')),
                ('userAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NUBER.Address')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='productSize',
            field=models.ManyToManyField(to='NUBER.ProductSize'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NUBER.Products'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='productColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NUBER.ProductColor'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NUBER.Country'),
        ),
    ]
